name: Deploy Masi Jewellers Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          echo "Starting deployment..."
          cd /var/www/elite-website
          
          # Pull latest changes
          git pull origin main
          
          # Restart services using existing script
          ./restart_services.sh
          
          # Wait for services to start
          sleep 15
          
          # Verify services are running
          curl -f http://localhost:3001/api/health || exit 1
          curl -f https://masijwellers.devforge.in/api/health || exit 1
          
          echo "Deployment completed successfully!"
