name: Deploy Masi Jewellers Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          echo "Starting deployment..."
          cd /var/www/elite-website
          pwd
          
          git pull origin main
          
          # Kill existing processes
          sudo pkill -f "elite-backend" || true
          sudo pkill -f "next dev" || true
          sleep 5
          
          # Start backend
          cd /var/www/elite-website/backend
          nohup cargo run > backend.log 2>&1 &
          
          # Start frontend
          cd /var/www/elite-website/frontend
          nohup npm run dev -- --port 3000 > frontend.log 2>&1 &
          
          # Wait and test
          sleep 15
          curl -f http://localhost:3001/api/health
          curl -f https://masijwellers.devforge.in/api/health
          
          echo "Deployment completed!"
